source 'https://rubygems.org'

gem 'rails', '4.0.1'
gem 'sass-rails', '~> 4.0.0'
gem 'compass-rails', '~> 1.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'sepastian-mongoid-rails4'
gem 'bson_ext'
gem 'haml'
gem 'draper'
